// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: proto/buffer.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BufferClient is the client API for Buffer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BufferClient interface {
	AllocateNew(ctx context.Context, in *BufferAllocateReq, opts ...grpc.CallOption) (*BufferAllocateRsp, error)
}

type bufferClient struct {
	cc grpc.ClientConnInterface
}

func NewBufferClient(cc grpc.ClientConnInterface) BufferClient {
	return &bufferClient{cc}
}

func (c *bufferClient) AllocateNew(ctx context.Context, in *BufferAllocateReq, opts ...grpc.CallOption) (*BufferAllocateRsp, error) {
	out := new(BufferAllocateRsp)
	err := c.cc.Invoke(ctx, "/idgen.Buffer/AllocateNew", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BufferServer is the server API for Buffer service.
// All implementations must embed UnimplementedBufferServer
// for forward compatibility
type BufferServer interface {
	AllocateNew(context.Context, *BufferAllocateReq) (*BufferAllocateRsp, error)
	mustEmbedUnimplementedBufferServer()
}

// UnimplementedBufferServer must be embedded to have forward compatible implementations.
type UnimplementedBufferServer struct {
}

func (UnimplementedBufferServer) AllocateNew(context.Context, *BufferAllocateReq) (*BufferAllocateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateNew not implemented")
}
func (UnimplementedBufferServer) mustEmbedUnimplementedBufferServer() {}

// UnsafeBufferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BufferServer will
// result in compilation errors.
type UnsafeBufferServer interface {
	mustEmbedUnimplementedBufferServer()
}

func RegisterBufferServer(s grpc.ServiceRegistrar, srv BufferServer) {
	s.RegisterService(&Buffer_ServiceDesc, srv)
}

func _Buffer_AllocateNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BufferAllocateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BufferServer).AllocateNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idgen.Buffer/AllocateNew",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BufferServer).AllocateNew(ctx, req.(*BufferAllocateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Buffer_ServiceDesc is the grpc.ServiceDesc for Buffer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Buffer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idgen.Buffer",
	HandlerType: (*BufferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateNew",
			Handler:    _Buffer_AllocateNew_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/buffer.proto",
}
